name: Draft Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
